apiVersion: apps/v1
kind: Deployment
metadata:
  name: kofiremote
spec:
  selector:
    matchLabels:
      app: kofiremoteapp
  replicas: 2
  template:
    metadata:
      labels:
        app: kofiremoteapp
    spec:
      containers:
      - name: kofiremoteapp
        image: etranzactgh/bank-registration-recorder:dev-1.0.0-SNAPSHOT.6
        ports:
        - containerPort: 5997
