apiVersion: apps/v1
kind: Deployment
metadata:
  name: kofimyapp
spec:
  selector:
    matchLabels:
      app: kofimyapp1
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
