apiVersion: apps/v1
kind: Deployment
metadata:
  name: kofiremote
spec:
  selector:
    matchLabels:
      app: kofiremoteapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: kofiremoteapp
        image: soloetzgh/remote:0.1
        ports:
        - containerPort: 8080
